name: Run Data Sync

on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * *'
  push:
    branches:
      - main

env:
  GITHUB_NAME: arthurfsy2
  GITHUB_EMAIL: fsyflh@gmail.com

jobs:
  sync:
    name: 同步
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 设置Python版本
        id: setup_python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: 'requirements.txt'

      - name: 安装依赖
        run: |
          pip install -r requirements.txt

      - name: 获取体重数据
        run: |
          python getWeightData.py ${{ secrets.ACCOUNT }} 
          
      - name: 检查文件更新
        id: check_changes
        run: |
          git diff --quiet || echo "::set-output name=changes::true"
      
      - name: 提交
        run: |
          git config --local user.email "${{ env.GITHUB_EMAIL }}"
          git config --local user.name "${{ env.GITHUB_NAME }}"
          git add .
          git diff --cached --quiet || git commit -m "已更新体重数据"
          if [[ "${{ steps.check_changes.outputs.changes }}" == "true" ]]; then
            git push
          else
            echo "No changes to push."
            git reset --hard HEAD  # 取消已经提交的文件变动
          fi