name: Run Data Sync

on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * *'
  push:
    branches:
      - main

env:
  GITHUB_NAME: arthurfsy2
  GITHUB_EMAIL: fsyflh@gmail.com

jobs:
  sync:
    name: 同步
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 设置Python版本
        id: setup_python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: 'requirements.txt'

      - name: 安装依赖
        run: |
          pip install -r requirements.txt

      - name: 获取体重数据
        run: |
          python getWeightData.py ${{ secrets.ACCOUNT }} 


      - name: 提交
        run: |
          git config --local user.email "${{ env.GITHUB_EMAIL }}"
          git config --local user.name "${{ env.GITHUB_NAME }}"
          git add .
          git commit -m '已更新体重数据' || echo "nothing to commit"
          git push || echo "nothing to push"
          
