name: Run Data Sync

on:
  workflow_dispatch:
  schedule:
    - cron: '00 01 * * *'
  push:
    branches:
      - main

jobs:
  sync:
    name: 同步
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 设置Python版本
        id: setup_python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: 'requirements.txt'

      - name: 安装依赖
        run: |
          pip install -r requirements.txt

      - name: 缓存体重数据    
        uses: actions/cache@v2    
        with:    
          path: ~/.yunmai  
          key: ${{ runner.os }}-yunmai-token-${{ github.actor }}
          
      - name: 使用缓存的体重数据      
        run: |       
          if [ -d ~/.yunmai ]; then  # 检查目录是否存在  
            echo "Data directory found, listing files:"   
            # 使用 ls 列出文件名，仅显示名称
            for file in ~/.yunmai/*; do
              if [ -f "$file" ]; then  # 如果是文件
                echo "$(basename "$file")"  # 只显示文件名
              fi
            done
          else    
            echo "Data directory not found!"     
          fi
      - name: 获取体重数据
        run: |
          mkdir -p ~/.yunmai
          python getWeightData.py ${{ secrets.ACCOUNT }}
      - name: 提交
        run: |
          current_time=$(date +'%Y-%m-%d %H:%M:%S %Z') # 获取当前时间并转换为中国时区时间
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "已更新体重数据，执行时间：${current_time}" || echo "nothing to commit"
          git push || echo "nothing to push"
